#!/bin/bash

CLK="10000000"
BAUD="256000"

verilator --trace \
   --cc ../../rtl/x_uart_tx.sv \
   --cc ../../lib/parallel_driver.cpp \
   --cc ../../lib/uart_sink.cpp \
   --exe x_uart_tx_tb.cpp \
   -I../../lib/include \
   -Gp_clk_hz=$CLK -Gp_baud=$BAUD 

make -C obj_dir -f Vx_uart_tx.mk Vx_uart_tx

./obj_dir/Vx_uart_tx $CLK $BAUD 100

