#!/bin/bash
set -e
echo "========================================================"
echo "Running synth..."

SYN_CMD=$(yosys \
   -p "read -sv ../rtl/x_uart_rx.sv" \
   -p "read -sv ../rtl/x_uart_tx.sv" \
   -p "read -sv ../verif/x_front_to_front/x_front_to_front.sv" \
   -p "chparam -set p_clk_hz $CLK 12000000" \
   -p "chparam -set p_baud $BAUD 115200" \
   -p "synth -top x_front_to_front" )

echo "========================================================"
echo "Running place and route..."
rm -f pnr.log
nextpnr-ice40 --hx8k --json x_front_to_front.json --package ct256 --pcf x_front_to_front.pcf --asc x_front_to_front.asc &> pnr.log
cat pnr.log | grep -A6 "Device utilisation"
echo "========================================================"
echo "Running Timing check..."
icetime -d hx8k x_front_to_front.asc > x_front_to_front.time
cat x_front_to_front.time
echo "========================================================"
echo "Packing..."
icepack x_front_to_front.asc x_front_to_front.bin
echo "========================================================"
echo "Writing..."
iceprog  -S x_front_to_front.bin
echo "========================================================"
