#!/bin/bash

FILENAME="synth.csv"
KEYWORD0="   Estimated number of transistors:"
KEYWORD1="+"

CLKS="10000000 20000000 40000000 80000000 160000000 320000000 640000000"
BAUDS="9600 14400 19200 38400 57600 115200 128000 256000"

> $FILENAME
for CLK in $CLKS 
do
   for BAUD in $BAUDS
   do
      # Get transistor count
      TRANSISTORS=$(yosys \
         -p "read -sv ../../rtl/x_uart_rx.sv" \
         -p "chparam -set p_clk_hz $CLK x_uart_rx" \
         -p "chparam -set p_baud $BAUD x_uart_rx" \
         -p "synth -top x_uart_rx" \
         -p "stat -tech cmos" \
         | grep "$KEYWORD0" \
         | sed -e "s/^$KEYWORD0//" -e "s/$KEYWORD1$//")
     
      # Error if no match
      if [ "$TRANSISTORS" = "" ]; then
         echo "No transistor match"
         exit 1;
      fi
      
      # Write to file
      ENTRY="$CLK,$BAUD,$TRANSISTORS" 
      echo $ENTRY
      echo $ENTRY >> $FILENAME
   done
done
